# Generated by Django 5.1.7 on 2025-04-08 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_review_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
