# Generated by Django 5.1.7 on 2025-04-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
