# Generated by Django 5.1.7 on 2025-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Not Paid'), ('R', 'Ready to Ship'), ('S', 'Shipped'), ('D', 'Delivered'), ('C', 'Canceled')], default='P', max_length=1),
        ),
    ]
